# Generated by Django 4.1.2 on 2023-04-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('basic_member', 'Basic Member'), ('pro_member', 'Pro Member'), ('moderator', 'Moderator')], default='basic_member', max_length=20),
        ),
    ]
