# Generated by Django 4.1.2 on 2023-05-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikidataEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post_default.jpg', upload_to='post_pics'),
        ),
        migrations.CreateModel(
            name='WikidataSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype_id', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='blog.wikidataentity')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='wikisubtypes',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.wikidatasubtype'),
        ),
        migrations.AddField(
            model_name='post',
            name='wikitags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.wikidataentity'),
        ),
    ]
