# Generated by Django 4.1.2 on 2023-05-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_wikidataentity_alter_post_image_wikidatasubtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='wikisubtypes',
        ),
        migrations.DeleteModel(
            name='WikidataSubtype',
        ),
    ]
