# Generated by Django 4.1.2 on 2023-04-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='policy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
